name: twifex
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - textstat
  - networkx
  - emoji
  - numpy
  - pandas
  - textblob
  - tqdm
  - nltk
  - pip
  - pip:
      - wordninja
      - urlextract
      - hatesonar
      - vaderSentiment