name: twifex
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - textstat
  - networkx
  - emoji
  - numpy
  - pandas
  - textblob
  - tqdm
  - nltk
  - spacy
  - beautifulsoup4
  - jupyterlab
  - pip
  - pip:
      - wordninja
      - urlextract
      - hatesonar
      - vaderSentiment
      - python-louvain
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz