name: twifex
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies
  - urlextract
  - textstat
  - networkx
  - emoji
  - numpy
  - vaderSentiment
  - hatesonar
  - pandas
  - textblob
  - tqdm
  - nltk
  - wordninja